"""empty message

Revision ID: a517d6050e24
Revises: 
Create Date: 2023-07-31 14:56:11.162495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a517d6050e24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencyTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newsletter_signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safetyplans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question1', sa.String(), nullable=True),
    sa.Column('question2', sa.String(), nullable=True),
    sa.Column('question3', sa.String(), nullable=True),
    sa.Column('question4', sa.String(), nullable=True),
    sa.Column('question5', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['agencyTypes.type_name'], name=op.f('fk_agencies_type_id_agencyTypes')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultationAgencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=True),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_consultationAgencies_agency_id_agencies')),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_consultationAgencies_consultation_id_consultations')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultationAgencies')
    op.drop_table('agencies')
    op.drop_table('safetyplans')
    op.drop_table('newsletter_signups')
    op.drop_table('consultations')
    op.drop_table('agencyTypes')
    # ### end Alembic commands ###
